### ISSUE TITLE
Missing Icons from PyPi package

### ISSUE THREAD

**Issue by zeldridge** [Bbalduzz/fluentflet#4]
Hey there,

when trying to use FluentIcon, you get this error: 

`FileNotFoundError: [Errno 2] No such file or directory: 'fluentflet\\static\\icons\\ic_fluent_toggle_left_24_regular.svg'`

Looking at your packaged library, I see that it's completely missing from the package and thus can't find them when using it.

**Comment by Bbalduzz** [comment]
Thank you for reporting this issue! You're absolutely right - I just checked and there's a problem with the static files (including icons) not being included in the built package.

I believe this is happening because Python's packaging system needs explicit configuration to include non-Python files.

I'll create a PR with these changes shortly.

**Comment by Bbalduzz** [comment]
Everything should work normally now. Updgrate `fluentflet ` to the `0.2.1a1` version 👍🏻
